#!/usr/bin/python
# -*- coding: utf-8 -*-
# 
__author__ = "Jerome Kieffer"
__license__ = "MIT"
__date__ = "23/09/2015" 

import os,sys
from yoctopuce import yocto_api 
from yoctopuce import yocto_humidity 
from yoctopuce import yocto_temperature 
from yoctopuce import yocto_pressure 


def die(msg):
    sys.exit(msg+' (check USB cable)')


def config(what):
    txt = ""
    if "temperature" in what:
        txt="""config meteo_temperature
graph_title Yoctopuce meteo temperature 
graph_vlabel degrees Celsius
graph_category sensors
graph_info This graph shows the temperature sensor of the Yoctopuce meteo
temp.info Temperature
temp.min -10
temp.label temp
"""
    elif "humidity" in what:
        txt = """config meteo_humidity
graph_title Yoctopuce meteo humidity 
graph_vlabel % Relative humidity
graph_category sensors
graph_info This graph shows the relative humidity sensor of the Yoctopuce meteo
rh.info Relative humidity
rh.min 0
rh.max 100
rh.label rh
"""
    elif "pressure" in what:
        txt = """config meteo_pressure
graph_title Yoctopuce meteo pressure
graph_vlabel Pressure (hPa)
graph_category sensors
graph_info This graph shows the presure sensor of the Yoctopuce meteo
graph_args --base 1000 -l 950 -u 1050 --rigid
pres.info Relative humidity %
pres.min 950
pres.max 1050
pres.label pres
"""
    print(txt)


def main(what):
    errmsg = yocto_api.YRefParam()
    # Setup the API to use local USB devices
    if yocto_api.YAPI.RegisterHub("usb", errmsg)!= yocto_api.YAPI.SUCCESS:
        sys.exit("init error: %s"%errmsg.value)
    
    # retreive any humidity sensor
    sensor = yocto_humidity.YHumidity.FirstHumidity()
    if sensor is None :
        die('No module connected')
    m = sensor.get_module()
    target = m.get_serialNumber()

    m = yocto_api.YModule.FindModule(target)

    if not m.isOnline(): 
        die('device not connected')

    if "humidity" in what:
        humSensor = yocto_humidity.YHumidity.FindHumidity(target+'.humidity')
        print("rh.value %5.2f" % humSensor.get_currentValue())
    elif "pressure" in what:
        pressSensor = yocto_pressure.YPressure.FindPressure(target+'.pressure')
        print("pres.value %6.1f" % pressSensor.get_currentValue())
    elif "temperature" in what:
        tempSensor = yocto_temperature.YTemperature.FindTemperature(target+'.temperature')
        print('temp.value %5.2f' % tempSensor.get_currentValue())

if __name__ == "__main__":
    if len(sys.argv)>1 and sys.argv[1] == "config":
        config(sys.argv[0])
    else:
        main(sys.argv[0])

