#!/usr/bin/python
# -*- coding: utf-8 -*-
# 
__author__ = "Jerome Kieffer"
__license__ = "MIT"
__date__ = "09/10/2015" 

height = 223
#corr_pres = (1 - 2.25577e-5*height)**-5.25588
#"ref: http://www.engineeringtoolbox.com/air-altitude-pressure-d_462.html"
"http://www.yoctopuce.com/FR/article/station-meteo-affichage"

import os,sys


def die(msg):
    sys.exit(msg+' (check USB cable)')


def config(what):
    txt = ""
    if "temperature" in what:
        txt="""config meteo_temperature
graph_title Yoctopuce meteo / DHT22 temperature 
graph_vlabel degrees Celsius
graph_category sensors
graph_info This graph shows the temperature sensor of the Yoctopuce meteo and DHT22
yocto.info Temperature
yocto.min -10
yocto.label Temperature inside
dht22.info Temperature
dht22.min -10
dht22.label Temperature outside
"""
    elif "humidity" in what:
        txt = """config meteo_humidity
graph_title Yoctopuce meteo / DHT22 humidity 
graph_vlabel % Relative humidity
graph_category sensors
graph_info This graph shows the relative humidity sensor of the Yoctopuce meteo and DHT22
yocto.info Relative humidity
yocto.min 0
yocto.max 100
yocto.label Humidity inside
dht22.info Relative humidity
dht22.min 0
dht22.max 100
dht22.label Humidity outside
"""
    elif "pressure" in what:
        txt = """config meteo_pressure
graph_title Yoctopuce meteo pressure
graph_vlabel Pressure (hPa)
graph_category sensors
graph_info This graph shows the presure sensor of the Yoctopuce meteo
graph_args --base 1000 -l 980 -u 1040 --rigid --units-exponent 0 -y 5:2
graph_scale no
pres.info Sealevel pressure (hPa)
pres.min 980
pres.max 1040
pres.label Pressure
"""
    print(txt)


def main(what):
    from yoctopuce import yocto_api 
    from yoctopuce import yocto_humidity 
    from yoctopuce import yocto_temperature 
    from yoctopuce import yocto_pressure 
    errmsg = yocto_api.YRefParam()



    # Setup the API to use local USB devices
    if yocto_api.YAPI.RegisterHub("usb", errmsg)!= yocto_api.YAPI.SUCCESS:
        sys.exit("init error: %s"%errmsg.value)
    
    # retreive any humidity sensor
    sensor = yocto_humidity.YHumidity.FirstHumidity()
    if sensor is None :
        die('No module connected')
    m = sensor.get_module()
    target = m.get_serialNumber()

    m = yocto_api.YModule.FindModule(target)

    if not m.isOnline(): 
        die('device not connected')

    if "pressure" in what:
        pressSensor = yocto_pressure.YPressure.FindPressure(target+'.pressure')
        tempSensor = yocto_temperature.YTemperature.FindTemperature(target+'.temperature')
        temp_abs = 273.15 + tempSensor.get_currentValue()
        corr_pres = ((temp_abs + 0.0065*height)/temp_abs) ** 5.2561
        print("pres.value %6.1f" % (pressSensor.get_currentValue()*corr_pres))
    else:
        import Adafruit_DHT
        sensor = Adafruit_DHT.DHT22
        pin = 21
        humidity, temperature = Adafruit_DHT.read_retry(sensor, pin)
        if "humidity" in what:
            humSensor = yocto_humidity.YHumidity.FindHumidity(target+'.humidity')
            print("yocto.value %5.2f" % humSensor.get_currentValue())
            if humidity is not None:
                print("dht22.value %5.2f"%humidity)
        elif "temperature" in what:
            tempSensor = yocto_temperature.YTemperature.FindTemperature(target+'.temperature')
            print('yocto.value %5.2f' % tempSensor.get_currentValue())
            if temperature is not None:
                print("dht22.value %5.2f"%temperature)


if __name__ == "__main__":
    if len(sys.argv)>1 and sys.argv[1] == "config":
        config(sys.argv[0])
    else:
        main(sys.argv[0])

